# This file was generated by GoReleaser. DO NOT EDIT.
cask "momentum" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "4e05eb4e1c408eca21b03ad7ef82995238392930ee0587800ed818abddb69738"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f75781f78cf8984939685ec77332238d48bbe31680c66b383327bbb93c6f325a"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71a87b0c75746030c5a3d593125d06104d1a848604932e76946697cc81f73e43"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c392c27239562e6ac94f10e389af4e5daf6956b9fa569084fa13f4c0a50781ad"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "momentum"
  desc "Lightweight CLI for managing Flux agents"
  homepage "https://github.com/sirsjg/momentum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "momentum"

  # No zap stanza required

end
