# This file was generated by GoReleaser. DO NOT EDIT.
cask "momentum" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "0fa4837be749fc1be3584f6cb510b12652c2ef9239bff715eb1af3398b985f23"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b6625fb8b57874b081a31a92109bdd64e8f42dcf7519401b5dd9e9e6548dba6"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7bcf8d3305236d933b3f90b16291fdf34bd714f00a86b0b5462f70e864722fe8"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "70e3ec8a8a988fb900d750e6ec113b3ae602b38b1e77ef53a50d0a235751937a"
      url "https://github.com/sirsjg/momentum/releases/download/v#{version}/momentum_#{version}_linux_arm64.tar.gz"
    end
  end

  name "momentum"
  desc "Lightweight CLI for managing Flux agents"
  homepage "https://github.com/sirsjg/momentum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "momentum"

  # No zap stanza required
end
