# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Momentum < Formula
  desc "Lightweight CLI for managing Flux agents"
  homepage "https://github.com/sirsjg/momentum"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.3/momentum_1.1.3_darwin_amd64.tar.gz"
      sha256 "4aca72b8958787d2dd0ab0d7e8efdfb7fc1e68968655d53578b21d395a47963c"

      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.3/momentum_1.1.3_darwin_arm64.tar.gz"
      sha256 "c97343103d2b24f5e2245c8abbb1f76370d4ad615d8edc552ce4534b55e6b20c"

      def install
        bin.install "momentum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.3/momentum_1.1.3_linux_amd64.tar.gz"
      sha256 "08e2e58a02687075e2036c402b3ec0c9bcecc7b22fc8e43d7526ca234923bf29"
      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.3/momentum_1.1.3_linux_arm64.tar.gz"
      sha256 "2d85382d2ebf645d3d434fd384642b4fb97ac561524c308391a6075e97fdd119"
      def install
        bin.install "momentum"
      end
    end
  end

  test do
    system "#{bin}/momentum", "--version"
  end
end
