# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Momentum < Formula
  desc "Lightweight CLI for managing Flux agents"
  homepage "https://github.com/sirsjg/momentum"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirsjg/momentum/releases/download/v1.3.1/momentum_1.3.1_darwin_amd64.tar.gz"
      sha256 "7c7417142a0faff9526d1701539909a53fe7dc2b82ed5985923c31430b5d1854"

      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirsjg/momentum/releases/download/v1.3.1/momentum_1.3.1_darwin_arm64.tar.gz"
      sha256 "303eab57ca2f02b7404f97cb8ccb6675ad73389b35968bd987df5cfa1b9c2b06"

      def install
        bin.install "momentum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/momentum/releases/download/v1.3.1/momentum_1.3.1_linux_amd64.tar.gz"
      sha256 "5de9c7802766c7f5041e2d6c2e53f9023014b1c58bc698d40b644bc509e01c7f"
      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/momentum/releases/download/v1.3.1/momentum_1.3.1_linux_arm64.tar.gz"
      sha256 "1d1be09929ed8733d99652c942a7255968c228a0d358d9d86bce7194fc49eb41"
      def install
        bin.install "momentum"
      end
    end
  end

  test do
    system "#{bin}/momentum", "--version"
  end
end
