# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Momentum < Formula
  desc "Lightweight CLI for managing Flux agents"
  homepage "https://github.com/sirsjg/momentum"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.0/momentum_1.1.0_darwin_amd64.tar.gz"
      sha256 "4958e65263ca06681b32cf72dd0a27f32e67c469235375168ddac85760f3e301"

      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.0/momentum_1.1.0_darwin_arm64.tar.gz"
      sha256 "4b5b853c6e36afd686ffa2621bcb0a8286bec23fc1061f39690d156c716ba094"

      def install
        bin.install "momentum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.0/momentum_1.1.0_linux_amd64.tar.gz"
      sha256 "a69d353e82b5ff047962ba088fe2cac38d1923db13003c24521a65d12ce33bd9"
      def install
        bin.install "momentum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/momentum/releases/download/v1.1.0/momentum_1.1.0_linux_arm64.tar.gz"
      sha256 "231c8da5319533e681ce20345df155c342c890f1a3639dc46fa3edfb5e06f82b"
      def install
        bin.install "momentum"
      end
    end
  end

  test do
    system "#{bin}/momentum", "--version"
  end
end
